# Site settings
title: Carpentries at Tufts
github_username: tufts-carpentries
description: >
 Carpentries at Tufts
url: "https://tuftscarp.github.io/"

# Build settings
markdown: kramdown
theme: jekyll-theme-slate

# plugins
plugins:
  - jekyll-redirect-from
